CompanyAssets/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyAssets.Web.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage="Please provide Name")]
        public string FullName { get; set; }
        [Required(ErrorMessage ="Select Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage ="Enter your email")]
        public string Email { get; set; }
        public string ImageUri { get; set; }
        public DateTime AddedOn { get; set; }
        public int DepartmentId { get; set; }
    }
}

CompanyAssets/Controllers/EmployeeController.cs
using CompanyAssets.Core.Models;
using CompanyAssets.Core.Repositories;
using CompanyAssets.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyAssets.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IGlobalService<Employee> _employeeService;
        public EmployeeController(IGlobalService<Employee> employeeService)
        {
            _employeeService = employeeService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]

        public IActionResult AddEmployee()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddEmployee(EmployeeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var _errors = new List<string>();
                foreach (var _values in ModelState.Values)
                {
                    foreach (var _error in _values.Errors)
                    {
                        _errors.Add(_error.ErrorMessage);
                    }
                }
                return Ok(new { check = false, message = string.Join(", ", _errors) });
            }
            try
            {

                var _depart = _employeeService.Add(new Employee
                {
                    AddedOn = DateTime.UtcNow.Date,
                    FullName = model.FullName,
                    Email = model.Email,
                    Gender = model.Gender,
                    DepartmentId = model.DepartmentId,
                    ImageUri = model.ImageUri

                });

                return RedirectToAction("LoadAll");
                //return Ok(new { check = true, message = "You have Successfully Registered.." });






            }
            catch (Exception ex)
            {
                return Ok(new { check = false, message = "Failed, please fill in all the required sections" });
            }

        }
        public ActionResult LoadAll()
        {
            var _employees = _employeeService.Search(x => true).OrderByDescending(x => x.AddedOn);

            var _empList = new List<EmployeeViewModel>();

            foreach (var _emp in _employees)
            {

                _empList.Add(new EmployeeViewModel
                {
                    Id = _emp.Id,
                    FullName = _emp.FullName,
                    Gender = _emp.Gender,
                    Email = _emp.Email,
                    ImageUri = _emp.ImageUri,
                    DepartmentId = _emp.DepartmentId

                });
            }

            return View(_empList);

        }

        public IActionResult GetEmployees()
        {
            var _emps = _employeeService.Search(x => true);
            return Ok(new { d = _emps });
        }

        public IActionResult DeleteEmployee(int id)
        {
            var _emp = _employeeService.Get(id);


            try
            {

                _employeeService.Delete(_emp);
                return RedirectToAction("LoadAll");

               // return Ok(new { check = true, message = "employee has been deleted successfully" });
            }
            catch (Exception ex)
            {


                return Ok(new { check = false, message = "Failed, try again" });
            }
            


        }
        public IActionResult ViewEmployee(int Id)
        {
            var _employee = _employeeService.Get(Id);

            return View(_employee);
        }

        public IActionResult EditEmployee(int Id)
        {
            var _emp = _employeeService.Get(Id);
            try
            {
                _employeeService.Update(_emp);
                return RedirectToAction("LoadAll");
            }
            catch (Exception ex)
            {


                return Ok(new { check = false, message = "Failed, try again" });
            }
        }
    }
}

CompanyAssets/Views/Employee/AddEmployee.cshtml
@using CompanyAssets.Web.Models
@model EmployeeViewModel

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form asp-controller="Employee" asp-action="AddEmployee" method="post" enctype="multipart/form-data">
                    <fieldset>



                        <div class="row">

                            <div class="col-md-4">
                                <div class="outer-1">
                                    <label>Add Picture</label>
                                    <img src="~/images/noimage.jpg" id="img" class="img-responsive inner-image" style="width:100%;" />
                                </div>
                                <input class="custom-file-upload" type="file" id="File" asp-for="ImageUri" data-btn-text="Select a File" accept=".png,.jpg,.jpeg" />
                            </div>
                            <div class="col-md-8">
                                <div class="row">

                                    <div class="col-md-4">
                                        <label>FullName</label>
                                        <!-- input -->
                                        <div class="fancy-form">

                                            <input type="text" class="form-control" id="title" asp-for="FullName" placeholder="Name">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <label>Select Gender</label>
                                        <div class="fancy-form fancy-form-select">
                                            <select class="form-control select2" id="gender" asp-for="Gender" name="Gender">
                                                <option value="">--- Select Class ---</option>
                                                <option>Male</option>
                                                <option>Female</option>
                                                
                                                
                                            </select>
                                            <i class="fancy-arrow-double"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <!-- select2 -->
                                        <label>Attach Department</label>
                                        <div class="fancy-form fancy-form-select">
                                            <select class="form-control select2" id="DepartmentId" asp-for="DepartmentId" name="DepartmentId">
                                                <option value="">--- Select Department ---</option>
                                            </select>
                                            <i class="fancy-arrow-double"></i>
                                        </div>
                                    </div>
                                </div>




                                <div class="row">

                                    <div class="col-md-6">
                                        <label>Email</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="email" class="form-control" id="email" asp-for="Email" placeholder="Enter email">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Added On</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="date" class="form-control" id="date" asp-for="AddedOn" placeholder="Select date">
                                        </div>
                                    </div>


                                </div>
                            </div>
                        </div>


                       



                        <div>
                            <button class="btn btn-danger btn-sm">Cancel</button>
                            <button class="btn btn-success btn-sm">Save</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(() => {


            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#img').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#File").change(function () {
                readURL(this);
            });
        

            fetch(`${window.location.origin}/department/Getdeparts`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error(response.statusText)
                    }
                    return response.json()
                })
                .then(result => {
                    result.d.forEach((element, index) => {
                        $('#DepartmentId').append(new Option(element.title, element.id));
                    });
                })
                .catch(error => {
                    console.log(error);
                    $('#DepartmentId').html(new Option('No departments', ''));
                });
        

            



        });
    </script>
}

CompanyAssets/Views/Employee/EditEmployee.cshtml
@using CompanyAssets.Core.Models
@model Employee
@{
    ViewData["Title"] = "ViewEmployee";
}



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">

                <div class="panel-heading">

                    <span class="elipsis">
                        <!-- panel title -->
                        <strong style="color:#fff;">EMPLOYEE [@Model.FullName]</strong>
                    </span>
                    <hr />



                </div>
            </div>

            <!-- panel content -->
            <div class="panel-body">
                <form id="form">
                    <input value="@Model.Id" id="Id" name="Id" type="hidden" />
                    <fieldset>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Profile Picture</label>
                                <div class="outer-1">
                                    <img src="@Model.ImageUri" id="img" class="img-responsive inner-image" style="width:100%;" />
                                </div>
                                <div class="margin-top-60">
                                    <span>
                                        <!-- panel title -->
                                        <a asp-action="DeleteEmployee" asp-route-id="@Model.Id" data-id="@Model.Id" class="btn btn-danger btn-sm hidden delete_me"><i class="fa fa-trash"></i>&nbsp;&nbsp; Delete</a>



                                    </span>


                                </div>





                            </div>
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Full Name</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" value="@Model.FullName" id="name" name="name" placeholder="Name" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Gender</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="gender" name="gender" placeholder="Gender" value="@Model.Gender" >
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Email</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="phone" name="Phone" placeholder="Contact" value="@Model.Email" >
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <label>Department</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="email" name="email" placeholder="email" value="@Model.DepartmentId" >
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <label>AddedOn</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="dateofbirth" name="Dateofbirth" placeholder="Null" value="@Model.AddedOn" >
                                        </div>
                                    </div>
                                </div>



                            </div>

                        </div>

                    </fieldset>
                </form>
            </div>
            <!-- /panel content -->

        </div>
    </div>
</div>

CompanyAssets/Views/Employee/LoadAll.cshtml
@using CompanyAssets.Web.Models
@model List<EmployeeViewModel>
@{
    ViewBag.Title = "Employees Page";

}


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">


                <div class="panel-heading">

                    <span class="elipsis">
                        <!-- panel title -->
                        <strong style="color:#ffffff;">ALL EMPLOYEES [@ViewBag.Count]</strong>  &nbsp;&nbsp;&nbsp;&nbsp; <a style="float:right; color:#ffffff;" href="~/employee/addemployee">Add new</a>
                    </span>
                </div>

            </div>
            <div class="card-body">

                <!-- panel content -->
                <div class="panel-body">
                    <table class="ui celled table table-hover table-condensed" id="asseetTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Full Name</th>
                                <th>Gender</th>
                                <th>Email</th>
                                <th>Department</th>
                                <th>AddedOn</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody id="departmentbody">
                            @{
                                if (Model != null)
                                {
                                    if (Model.Count != 0)
                                    {
                                        var index = 1;
                                        foreach (var _emp in Model)
                                        {
                                            <tr class="tr_col" style="cursor:pointer;" onclick="window.location.href = `${window.location.origin}/employee/viewemployee/@_emp.Id`">
                                                <td>@index</td>
                                                <td>@_emp.FullName</td>
                                                <td>@_emp.Gender</td>
                                                <td>@_emp.Email</td>
                                                <td class="center">@_emp.DepartmentId</td>
                                                <td class="center">@_emp.AddedOn</td>
                                                <td>
                                                    <button type="button" class="btn btn-sm btn-success" href="~/employee/editemployee" id="">Edit</button>
                                                    <button type="button" class="btn btn-sm btn btn-primary" onclick="window.location.href = `${window.location.origin}/employee/viewemployee/@_emp.Id`">View</button>
                                                </td>

                                            </tr>
                                            index++;
                                        }
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /panel content -->

                <div></div>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(() => {
            $('table').DataTable({
                dom: 'Bfrtip',
                lengthMenu: [
                    [10, 25, 50, -1],
                    ['10 rows', '25 rows', '50 rows', 'Show all']
                ],
                buttons: [
                    'pageLength',
                    {
                        extend: 'excel',
                    },
                    {
                        extend: 'pdf',
                        messageBottom: null
                    },
                    {
                        extend: 'print',
                        messageTop: null,
                        messageBottom: null
                    }
                ],
                responsive: true,

            });



        });
    </script>
}

CompanyAssets/Views/Employee/ViewEmployee.cshtml
@using CompanyAssets.Core.Models
@model Employee
@{
    ViewData["Title"] = "ViewEmployee";
}



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">

                <div class="panel-heading">

                    <span class="elipsis">
                        <!-- panel title -->
                        <strong style="color:#fff;">EMPLOYEE [@Model.FullName]</strong>
                    </span>
                    <hr />

                    

                </div>
            </div>

            <!-- panel content -->
            <div class="panel-body">
                <form id="form">
                    <input value="@Model.Id" id="Id" name="Id" type="hidden" />
                    <fieldset>
                        <div class="row">
                            <div class="col-md-4">
                                <label>Profile Picture</label>
                                <div class="outer-1">
                                    <img src="@Model.ImageUri" id="img" class="img-responsive inner-image" style="width:100%;" />
                                </div>
                                <div class="margin-top-60">
                                    <span>
                                        <!-- panel title -->
                                        <a asp-action="DeleteEmployee" asp-route-id="@Model.Id" data-id="@Model.Id" class="btn btn-danger btn-sm hidden delete_me"><i class="fa fa-trash"></i>&nbsp;&nbsp; Delete</a>
                                        
                                        

                                    </span>


                                </div>





                            </div>
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Full Name</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" value="@Model.FullName" id="name" name="name" placeholder="Name" readonly>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Gender</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="gender" name="gender" placeholder="Gender" value="@Model.Gender" readonly>
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Email</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="phone" name="Phone" placeholder="Contact" value="@Model.Email" readonly>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <label>Department</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="email" name="email" placeholder="email" value="@Model.DepartmentId" readonly>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <label>AddedOn</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="dateofbirth" name="Dateofbirth" placeholder="Null" value="@Model.AddedOn" readonly>
                                        </div>
                                    </div>
                                </div>
                                
                                

                            </div>

                        </div>

                    </fieldset>
                </form>
            </div>
            <!-- /panel content -->

        </div>
    </div>
</div>