CompanyAssets/Models/DepartmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyAssets.Web.Models
{
    public class DepartmentViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Please Add Title")]
        public string Title { get; set; }
        [Required(ErrorMessage ="Add Description")]
        public string Description { get; set; }
        public string DepartmentHead { get; set; }
        public int EmployeeId { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}

CompanyAssets/Controllers/DepartmentController.cs
using CompanyAssets.Core.Models;
using CompanyAssets.Core.Repositories;
using CompanyAssets.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyAssets.Web.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IGlobalService<Department> _departService;
        public DepartmentController(IGlobalService<Department> departService)
        {
            _departService = departService;  
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]

        public IActionResult AddDepartment()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddDepartment(DepartmentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var _errors = new List<string>();
                foreach (var _values in ModelState.Values)
                {
                    foreach (var _error in _values.Errors)
                    {
                        _errors.Add(_error.ErrorMessage);
                    }
                }
                return Ok(new { check = false, message = string.Join(", ", _errors) });
            }
            try
            {

                var _depart = _departService.Add(new Department
                {
                    CreatedOn = DateTime.UtcNow.Date,
                     Title=model.Title,
                     Description=model.Description,
                      DepartmentHead=model.DepartmentHead

                });

                return RedirectToAction("LoadAll");
                //return Ok(new { check = true, message = "You have Successfully Registered.." });
                





            }
            catch (Exception ex)
            {
                return Ok(new { check = false, message = "Failed, please fill in all the required sections" });
            }

        }
        public ActionResult LoadAll()
        {
            var _departs = _departService.Search(x => true).OrderByDescending(x => x.CreatedOn);

            var _departList = new List<DepartmentViewModel>();

            foreach (var _depart in _departs)
            {
                
                _departList.Add(new DepartmentViewModel
                {
                    Id = _depart.Id,
                    Title = _depart.Title,
                    Description = _depart.Description,
                    DepartmentHead = _depart.DepartmentHead,
                    CreatedOn = _depart.CreatedOn
                    
                });
            }

            return View(_departList);

        }

        public IActionResult DeleteDepartment(int id)
        {
            var _depart = _departService.Get(id);


            try
            {

                _departService.Delete(_depart);
                return RedirectToAction("LoadAll");

                // return Ok(new { check = true, message = "employee has been deleted successfully" });
            }
            catch (Exception ex)
            {


                return Ok(new { check = false, message = "Failed, try again" });
            }



        }


        public IActionResult Getdeparts()
        {
            var _departs = _departService.Search(x => true);
            return Ok(new { d = _departs });
        }
        public IActionResult ViewDepartment(int Id)
        {
            var _depart = _departService.Get(Id);

            return View(_depart);
        }
        public IActionResult EditDepartment(int Id)
        {
            var _asset = _departService.Get(Id);
            try
            {
                _departService.Update(_asset);
                return RedirectToAction("LoadAll");
            }
            catch (Exception ex)
            {


                return Ok(new { check = false, message = "Failed, try again" });
            }
        }
    }
}

CompanyAssets/Views/Department/AddDepartment.cshtml
@using CompanyAssets.Web.Models
@model DepartmentViewModel

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form asp-controller="Department" asp-action="AddDepartment" method="post" enctype="multipart/form-data">
                    <fieldset>



                        <div class="row">
                            <div class="col-md-6">
                                <label>Title</label>
                                <!-- input -->
                                <div class="fancy-form">

                                    <input type="tel" class="form-control" id="title" asp-for="Title" placeholder="Title">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Description</label>
                                <!-- input -->
                                <div class="fancy-form">
                                    <input type="tel" class="form-control" id="description" asp-for="Description" placeholder="Description">
                                </div>
                            </div>
                        </div>
                        <div class="row">



                            <!--<div class="col-md-6">
                            <label>Department Head</label>-->
                            <!-- input -->
                            <!--<div class="fancy-form">
                                    <input type="text" class="form-control" id="head" asp-for="DepartmentHead" placeholder="HeadedBy">
                                </div>
                            </div>-->
                            <div class="col-md-6">
                                <!-- select2 -->
                                <label>Headed By</label>
                                <div class="fancy-form fancy-form-select">
                                    <select class="form-control select2" id="EmployeeId" asp-for="EmployeeId" name="EmployeeId">
                                        <option value="">--- Select Head ---</option>
                                    </select>
                                    <i class="fancy-arrow-double"></i>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Created On</label>
                                <input type="date" class="form-control" id="head" asp-for="DepartmentHead" placeholder="HeadedBy">

                            </div>

                        </div>



                        <div>
                            <button class="btn btn-danger btn-sm">Cancel</button>
                            <button class="btn btn-success btn-sm">Save</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(() => {


            fetch(`${window.location.origin}/employee/getemployees`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error(response.statusText)
                    }
                    return response.json()
                })
                .then(result => {
                    result.d.forEach((element, index) => {
                        $('#EmployeeId').append(new Option(element.title, element.id));
                    });
                })
                .catch(error => {
                    console.log(error);
                    $('#EmployeeId').html(new Option('No Employees', ''));
                });
        

        });
    </script>
}

CompanyAssets/Views/Department/EditDepartment.cshtml
@using CompanyAssets.Core.Models
@model Department
@{
    ViewData["Title"] = "ViewDepartment";
}



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">

                <div class="panel-heading">

                    <span class="elipsis">
                        <!-- panel title -->
                        <strong style="color:#fff;">DEPARTMENT [@Model.Title]</strong>
                    </span>
                    <hr />



                </div>
            </div>

            <!-- panel content -->
            <div class="panel-body">
                <form id="form">
                    <input value="@Model.Id" id="Id" name="Id" type="hidden" />
                    <fieldset>
                        <div class="row">

                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Full Name</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" value="@Model.Title" id="title" name="title" placeholder="Name" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Gender</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="gender" name="gender" placeholder="Gender" value="@Model.Description" >
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Email</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="phone" name="Phone" placeholder="Contact" value="@Model.CreatedOn" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Department</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="email" name="email" placeholder="email" value="@Model.DepartmentHead" >
                                        </div>
                                    </div>

                                </div>
                                <div class="margin-top-60">
                                    <span>
                                        <!-- panel title -->
                                        <a asp-action="DeleteDepartment" asp-route-id="@Model.Id" data-id="@Model.Id" class="btn btn-danger btn-sm hidden delete_me"><i class="fa fa-trash"></i>&nbsp;&nbsp; Delete</a>



                                    </span>


                                </div>



                            </div>

                        </div>

                    </fieldset>
                </form>
            </div>
            <!-- /panel content -->

        </div>
    </div>
</div>

CompanyAssets/Views/Department/LoadAll.cshtml
@using CompanyAssets.Web.Models
@model List<DepartmentViewModel>
@{
    ViewBag.Title = "Departments Page";

}


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">
            

                <div class="panel-heading">

                    <span class="elipsis">
                        <!-- panel title -->
                        <strong style="color:#ffffff;">ALL DEPARTMENTS [@ViewBag.Count]</strong>  &nbsp;&nbsp;&nbsp;&nbsp; <a style="float:right; color:#ffffff;" href="~/department/adddepartment">Add new</a>
                    </span>
                </div>

                </div>
            <div class="card-body">

                <!-- panel content -->
                <div class="panel-body">
                    <table class="ui celled table table-hover table-condensed" id="departmentTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Headed By</th>
                                <th>Created On</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody id="departmentbody">
                            @{
                                if (Model != null)
                                {
                                    if (Model.Count != 0)
                                    {
                                        var index = 1;
                                        foreach (var _depart in Model)
                                        {
                                            <tr class="tr_col" style="cursor:pointer;" onclick="window.location.href = `${window.location.origin}/department/viewdepartment/@_depart.Id`">
                                                <td>@index</td>
                                                <td>@_depart.Title</td>
                                                <td>@_depart.Description</td>
                                                <td>@_depart.DepartmentHead</td>
                                                <td class="center">@_depart.CreatedOn</td>
                                                <td>
                                                    <button type="button" class="btn btn-sm btn-success"href="~/department/editdepartment" id="">Edit</button>
                                                    <button type="button" class="btn btn-sm btn-danger" id="">View</button>
                                                </td>

                                            </tr>
                                            index++;
                                        }
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /panel content -->

                <div></div>
                </div>
            </div>
        </div>
    </div>



@section Scripts{
    <script>
        $(document).ready(() => {
            $('table').DataTable({
                dom: 'Bfrtip',
                lengthMenu: [
                    [10, 25, 50, -1],
                    ['10 rows', '25 rows', '50 rows', 'Show all']
                ],
                buttons: [
                    'pageLength',
                    {
                        extend: 'excel',
                    },
                    {
                        extend: 'pdf',
                        messageBottom: null
                    },
                    {
                        extend: 'print',
                        messageTop: null,
                        messageBottom: null
                    }
                ],
                responsive: true,

            });
        });
    </script>
}

CompanyAssets/Views/Department/ViewDepartment.cshtml
@using CompanyAssets.Core.Models
@model Department
@{
    ViewData["Title"] = "ViewDepartment";
}



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">

                <div class="panel-heading">

                    <span class="elipsis">
                        <!-- panel title -->
                        <strong style="color:#fff;">DEPARTMENT [@Model.Title]</strong>
                    </span>
                    <hr />



                </div>
            </div>

            <!-- panel content -->
            <div class="panel-body">
                <form id="form">
                    <input value="@Model.Id" id="Id" name="Id" type="hidden" />
                    <fieldset>
                        <div class="row">
                            
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Full Name</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" value="@Model.Title" id="title" name="title" placeholder="Name" readonly>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Gender</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="gender" name="gender" placeholder="Gender" value="@Model.Description" readonly>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Email</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="phone" name="Phone" placeholder="Contact" value="@Model.CreatedOn" readonly>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Department</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="email" name="email" placeholder="email" value="@Model.DepartmentHead" readonly>
                                        </div>
                                    </div>

                                </div>
                                <div class="margin-top-60">
                                    <span>
                                        <!-- panel title -->
                                        <a asp-action="DeleteDepartment" asp-route-id="@Model.Id" data-id="@Model.Id" class="btn btn-danger btn-sm hidden delete_me"><i class="fa fa-trash"></i>&nbsp;&nbsp; Delete</a>



                                    </span>


                                </div>



                            </div>

                        </div>

                    </fieldset>
                </form>
            </div>
            <!-- /panel content -->

        </div>
    </div>
</div>