CompanyAssets/Controllers/AssetController.cs
using CompanyAssets.Core.Models;
using CompanyAssets.Core.Repositories;
using CompanyAssets.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyAssets.Web.Controllers
{
    public class AssetController : Controller
    {
        private readonly IGlobalService<Asset> _assetService;
        public AssetController(IGlobalService<Asset> assetService)
        {
            _assetService = assetService;
        }
        [HttpGet]
        public IActionResult AddAsset()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddAsset(NewAssetViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var _errors = new List<string>();
                foreach (var _values in ModelState.Values)
                {
                    foreach (var _error in _values.Errors)
                    {
                        _errors.Add(_error.ErrorMessage);
                    }
                }
                return Ok(new { check = false, message = string.Join(", ", _errors) });
            }
            try
            {

                var _asset = _assetService.Add(new Asset
                {
                    CreatedOn = DateTime.UtcNow.Date,
                    Title = model.Title,
                    Description = model.Description,
                    IsDeleted = false,
                    DepartmentId=model.DepartmentId

                });

                return RedirectToAction("LoadAll");
            }
            catch (Exception ex)
            {
                return Ok(new { check = false, message = "Failed, please fill in all the required sections" });
            }
        }

        public IActionResult LoadAll()
        {
            var _assets = _assetService.Search(x => true).OrderByDescending(x => x.CreatedOn);

            var _assetList = new List<NewAssetViewModel>();

            foreach (var _asset in _assets)
            {

                _assetList.Add(new NewAssetViewModel
                {
                    AssetId = _asset.AssetId,
                    Title = _asset.Title,
                    Description = _asset.Description,
                   
                    CreatedOn = _asset.CreatedOn

                });
            }

            return View(_assetList);
        }
        public IActionResult EditAsset()
        {
            return View();
        }
        public IActionResult DeleteAsset()
        {
            return View();
        }
        public IActionResult ViewAsset(int Id)
        {
            var _asset = _assetService.Get(Id);

            return View(_asset);
        }
        public IActionResult DeleteAsset(int id)
        {
            var _asset = _assetService.Get(id);


            try
            {

                _assetService.Delete(_asset);
                return RedirectToAction("LoadAll");

                // return Ok(new { check = true, message = "employee has been deleted successfully" });
            }
            catch (Exception ex)
            {


                return Ok(new { check = false, message = "Failed, try again" });
            }

        }
        public IActionResult EditAsset(int Id)
        {
            var _asset = _assetService.Get(Id);
            try
            {
                _assetService.Update(_asset);
                return RedirectToAction("LoadAll");
            }
            catch (Exception ex)
            {


                return Ok(new { check = false, message = "Failed, try again" });
            }
        }

    }
}

CompanyAssets/Views/Asset/AddAsset.cshtml
@using CompanyAssets.Web.Models
@model NewAssetViewModel

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form asp-controller="Asset" asp-action="AddAsset" method="post" enctype="multipart/form-data">
                    <fieldset>



                        <div class="row">
                            <div class="col-md-6">
                                <label>Title</label>
                                <!-- input -->
                                <div class="fancy-form">

                                    <input type="tel" class="form-control" id="title" asp-for="Title" placeholder="Title">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Description</label>
                                <!-- input -->
                                <div class="fancy-form">
                                    <input type="text" class="form-control" id="description" asp-for="Description" placeholder="Description">
                                </div>
                            </div>
                        </div>
                        <div class="row">



                            <div class="col-md-6">
                                <!-- select2 -->
                                <label>Attach Department</label>
                                <div class="fancy-form fancy-form-select">
                                    <select class="form-control select2" id="DepartmentId" asp-for="DepartmentId" name="DepartmentId">
                                        <option value="">--- Select Department ---</option>
                                    </select>
                                    <i class="fancy-arrow-double"></i>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Created On</label>
                                <input type="date" class="form-control" id="head" asp-for="CreatedOn" placeholder="date">

                            </div>

                        </div>



                        <div>
                            <button class="btn btn-danger btn-sm">Cancel</button>
                            <button class="btn btn-success btn-sm">Save</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(() => {

            fetch(`${window.location.origin}/department/Getdeparts`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error(response.statusText)
                    }
                    return response.json()
                })
                .then(result => {
                    result.d.forEach((element, index) => {
                        $('#DepartmentId').append(new Option(element.title, element.id));
                    });
                })
                .catch(error => {
                    console.log(error);
                    $('#DepartmentId').html(new Option('No departments', ''));
                });


            
        });
    </script>
}

CompanyAssets/Views/Asset/EditAsset.cshtml
@using CompanyAssets.Core.Models
@model Asset
@{
    ViewData["Title"] = "ViewAsset";
}



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">


            </div>

            <!-- panel content -->
            <div class="panel-body">
                <form id="form">
                    <fieldset>
                        <div class="row">
                            <div class="col-md-4">

                                <div class="margin-top-60">
                                    <span>
                                        <!-- panel title -->
                                        <a asp-action="DeleteAsset" asp-route-id="@Model.AssetId" data-id="@Model.AssetId" class="btn btn-danger btn-sm hidden delete_me"><i class="fa fa-trash"></i>&nbsp;&nbsp; Delete</a>



                                    </span>


                                </div>





                            </div>
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Title</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" value="@Model.Title" id="name" name="name" placeholder="Name" >
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Description</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="gender" name="gender" placeholder="Gender" value="@Model.Description" >
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Department</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="phone" name="Phone" placeholder="Contact" value="@Model.DepartmentId" >
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <label>AddedOn</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="dateofbirth" name="Dateofbirth" placeholder="Null" value="@Model.CreatedOn" >
                                        </div>
                                    </div>
                                </div>



                            </div>

                        </div>

                    </fieldset>
                </form>
            </div>
            <!-- /panel content -->

        </div>
    </div>
</div>

CompanyAssets/Views/Asset/LoadAll.cshtml
@using CompanyAssets.Web.Models
@model List<NewAssetViewModel>
@{
    ViewBag.Title = "Assets Page";

}


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">


                <div class="panel-heading">

                    <span class="elipsis">
                        <!-- panel title -->
                        <strong style="color:#ffffff;">ALL ASSETS [@ViewBag.Count]</strong>  &nbsp;&nbsp;&nbsp;&nbsp; <a style="float:right; color:#ffffff;" href="~/asset/addasset">Add new</a>
                    </span>
                </div>

            </div>
            <div class="card-body">

                <!-- panel content -->
                <div class="panel-body">
                    <table class="ui celled table table-hover table-condensed" id="asseetTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Department</th>
                                <th>Created On</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody id="departmentbody">
                            @{
                                if (Model != null)
                                {
                                    if (Model.Count != 0)
                                    {
                                        var index = 1;
                                        foreach (var _asset in Model)
                                        {
                                            <tr class="tr_col" style="cursor:pointer;" onclick="window.location.href = `${window.location.origin}/asset/viewasset/@_asset.AssetId`">
                                                <td>@index</td>
                                                <td>@_asset.Title</td>
                                                <td>@_asset.Description</td>
                                                <td>@_asset.DepartmentId</td>
                                                <td class="center">@_asset.CreatedOn</td>
                                                <td>
                                                    <button type="button" class="btn btn-sm btn-success" href="~/asset/editasset" id="">Edit</button>
                                                    <button type="button" class="btn btn-sm btn-danger" id="">View</button>
                                                </td>

                                            </tr>
                                            index++;
                                        }
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /panel content -->

                <div></div>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(() => {
            $('table').DataTable({
                dom: 'Bfrtip',
                lengthMenu: [
                    [10, 25, 50, -1],
                    ['10 rows', '25 rows', '50 rows', 'Show all']
                ],
                buttons: [
                    'pageLength',
                    {
                        extend: 'excel',
                    },
                    {
                        extend: 'pdf',
                        messageBottom: null
                    },
                    {
                        extend: 'print',
                        messageTop: null,
                        messageBottom: null
                    }
                ],
                responsive: true,

            });



        });
    </script>
}

CompanyAssets/Views/Asset/ViewAsset.cshtml
@using CompanyAssets.Core.Models
@model Asset
@{
    ViewData["Title"] = "ViewAsset";
}



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-info">

                
            </div>

            <!-- panel content -->
            <div class="panel-body">
                <form id="form">
                    <fieldset>
                        <div class="row">
                            <div class="col-md-4">
                                
                                <div class="margin-top-60">
                                    <span>
                                        <!-- panel title -->
                                        <a asp-action="DeleteAsset" asp-route-id="@Model.AssetId" data-id="@Model.AssetId" class="btn btn-danger btn-sm hidden delete_me"><i class="fa fa-trash"></i>&nbsp;&nbsp; Delete</a>



                                    </span>


                                </div>





                            </div>
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Title</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" value="@Model.Title" id="name" name="name" placeholder="Name" readonly>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Description</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="gender" name="gender" placeholder="Gender" value="@Model.Description" readonly>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <label>Department</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="phone" name="Phone" placeholder="Contact" value="@Model.DepartmentId" readonly>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-4">
                                        <label>AddedOn</label>
                                        <!-- input -->
                                        <div class="fancy-form">
                                            <input type="tel" class="form-control" id="dateofbirth" name="Dateofbirth" placeholder="Null" value="@Model.CreatedOn" readonly>
                                        </div>
                                    </div>
                                </div>



                            </div>

                        </div>

                    </fieldset>
                </form>
            </div>
            <!-- /panel content -->

        </div>
    </div>
</div>